FROM python:3.10-slim
WORKDIR /centralized
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY centralized/ ./centralized/
COPY feature_extractor.py .
ENV PYTHONUNBUFFERED=1
CMD ["python", "./centralized/server.py"]
